### PR TITLE
Adding a Progressive Web App icon

### PR DESCRIPTION
**Pull request by jasonmadigan**
Hi!

We're adding one or two more types of client for some Mobile apps, and we'd like to add an icon[1] for Progressive Web Apps. Think I've got everything lined up, but do let me know if there's anything I'm missing.

screen shot 2018-06-18 at 15 29 11

[1] https://github.com/webmaxru/progressive-web-apps-logo

### CODE REVIEW

**Comment by rhamilto** [comment]
Hi, @jasonmadigan.  Sorry to have missed this PR (Github notification fail?).  Do you still desire to add these icons?  If so, you'll need to update the PR (a simple rebase won't work since additional icons have been added).

**Comment by jasonmadigan** [comment]
hey @rhamilto - no worries. I'll take a look at re-adding this & https://github.com/openshift/openshift-logos-icon/pull/20

I could add these in PR if that's preferable?

**Comment by rhamilto** [comment]
A single PR with both icons is great.  Thanks, @jasonmadigan.

**Pull request closed without merging**
